/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ktlint.sample

class Library {
    fun someLibraryMethod(): Boolean {




        // TOO many lines to trigger ktlint failure




        return true
    }
}
